# Generated by Django 4.0 on 2022-01-04 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='src/image')),
                ('bin_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bin.bin')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
