# Generated by Django 4.0 on 2022-01-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='bin_id',
            new_name='bin',
        ),
    ]
