# Generated by Django 4.0 on 2022-01-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_rename_bin_id_image_bin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='bin',
            new_name='bin_id',
        ),
    ]
