# Generated by Django 4.0.1 on 2022-01-12 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_rename_bin_image_bin_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='wmtss_image',
        ),
    ]
