# Generated by Django 4.0.1 on 2022-02-05 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bin', '0002_alter_bin_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='src/image')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bin.bin')),
            ],
            options={
                'db_table': 'wmtss_image',
            },
        ),
    ]
