# Generated by Django 4.0.1 on 2022-02-05 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bin', '0002_alter_bin_tag'),
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bin_id', to='bin.bin'),
        ),
    ]
